doctrine_cache:
  providers:
    liip_imagine:
      type: redis
      redis:
        connection_id: kunstmaan_extra.redis_client

    user_info:
      type: redis
      redis:
        connection_id: kunstmaan_extra.redis_client
