imports:
    - { resource: parameters.yml }
    - { resource: env_parameters.php }
    - { resource: security.yml }
    - { resource: pages.yml }

framework:
    esi:             ~
    translator:      { fallback: "en" }
    secret:          "25WBznx6VuwnZnqq6xGKWh9N"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        strict_email: true
    templating:
        engines: ['twig']
    default_locale:  "en"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug:          false
    use_controller: false
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
