fos_http_cache:
    cache_control:
        rules:
            # match admin area
            -
                match:
                    path: ^/admin
                headers:
                    cache_control:
                        public: false
                        max_age: 0
                        s_maxage: 0
                    last_modified: "-1 hour"
