kunstmaan_extra:
    tinypng_api_key: 2IgQvBB70SBuavZXdsUUmTR5EoWdq3hN

liip_imagine:
    filter_sets:
        frame:
            filters:
                crop:
                  start: [0, 0]
                  size:  [488, 670]
        frame_thumb:
            filters:
                crop:
                    start: [0, 0]
                    size:  [488, 670]
                thumbnail:
                    size: [146, 200]
                    mode: outbound
        card:
            filters:
                thumbnail: { size: [231, 331], mode: outbound }
                relative_resize: { widen: 231 }
            post_processors:
                tinypng_com: ~
