farming_logs:
    path: /farming/{id}.{_format}
    defaults:
      _controller: nassau.cartoon_battle.controller.game.farming_controller:farming

farming_setup:
    path: /game/farming
    defaults:
      _controller: nassau.cartoon_battle.controller.game.farming_setup_controller:setup

kongregate_auth:
    path: /api/kongregate/login
    defaults:
      _controller: nassau.cartoon_battle.controller.kongregate_authorization_controller:getUser

paypal_ipn:
    path: /paypal
    defaults:
      _controller: nassau.cartoon_battle.controller.paypal.instant_payment_notification_controller:listener

game_echo:
    path: /game/echo/{message}
    defaults:
      _controller: nassau.cartoon_battle.controller.game.echo_controller

harvesting_deck:
    path: /enemy-deck/{enemy}
    defaults:
      _controller: CartoonBattleBundle:Harvesting:deck

rumble_stats:
    path: /rumble-stats/{id}/{rumble}.csv
    defaults:
      _controller: CartoonBattleBundle:RumbleStats:scores

rumble_stats_header:
    path: /rumble-stats-header/{id}.csv
    defaults:
      _controller: CartoonBattleBundle:RumbleStats:header

cartoonbattlebundle_rumble_standings:
    resource: '@CartoonBattleBundle/Controller/RumbleStandingsController.php'
    type:     annotation
    prefix:   /api/

cartoonbattlebundle_unit_admin_list:
    resource: '@CartoonBattleBundle/Controller/UnitAdminListController.php'
    type:     annotation
    prefix:   /admin/unit/

cartoonbattlebundle_guild_admin_list:
    resource: '@CartoonBattleBundle/Controller/GuildAdminListController.php'
    type:     annotation
    prefix:   /admin/guild/

cartoonbattlebundle_rumble_admin_list:
    resource: '@CartoonBattleBundle/Controller/RumbleAdminListController.php'
    type:     annotation
    prefix:   /admin/rumble/
